vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    media:
      uri_prefix: /media
      upload_destination: '%kernel.project_dir%/public/media'
      directory_namer:
        service: vich_uploader.namer_directory_property
        options: { property: 'slugMedia', transliterate: true }
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_remove: true # determine whether to delete file upon removal of entity
      delete_on_update: true # determine wheter to delete the file upon update of entity
      inject_on_load: false # determine whether to inject a File instance upon load
